# Generated by Django 3.1.7 on 2021-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210309_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_custom',
            old_name='link',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='link',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='link',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
