# Generated by Django 3.1.7 on 2021-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210310_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
