# Generated by Django 3.1.7 on 2021-03-12 12:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20210310_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('slug', models.SlugField(blank=True)),
                ('pdf_task', models.FileField(upload_to='foo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.section')),
            ],
        ),
        migrations.CreateModel(
            name='UploadAnswerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('pdf_answer', models.FileField(upload_to='pdfAnswer/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.uploadtask')),
                ('studentUpload', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
            ],
        ),
    ]
