# Generated by Django 3.1.7 on 2021-03-17 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_uploadanswertask_uploadtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
