# Generated by Django 3.1.7 on 2021-03-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210323_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultuploadanswertask',
            name='student',
        ),
        migrations.AddField(
            model_name='resultuploadanswertask',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultuploadanswertask',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
