# Generated by Django 3.1.7 on 2021-03-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_uploadanswertask_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultuploadanswertask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.uploadanswertask'),
        ),
    ]
