# Generated by Django 3.1.7 on 2021-05-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210325_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultquiz',
            name='user',
        ),
        migrations.AddField(
            model_name='resultquiz',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.student'),
        ),
    ]
