# Generated by Django 3.1.7 on 2021-05-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210521_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='amountPoint',
            field=models.FloatField(default=0),
        ),
    ]
