# Generated by Django 3.1.7 on 2021-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210522_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='str'),
        ),
    ]
