# Generated by Django 3.1.7 on 2021-05-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210524_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
