# Generated by Django 3.1.7 on 2021-05-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_course_coursepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
